@startuml

class Main {
    + main(String[] args)
}

class Faktura {
    - fakturaData: Date
    - sprzedawca: Sklep
    - kupujacy: Sklep
    - przedmioty: ArrayList<Produkty>
    + Faktura(fakturaData: Date, sprzedawca: Sklep, kupujacy: Sklep)
    + podajDate(): Date
    + cenaNetto(): double
    + wartoscVAT(): double
    + CenaKoncowa(): double
    + dodajProdukt(produkt: Produkty): void
    + podajProdukty(): ArrayList<Produkty>
}

class Sklep {
    - nazwa: String
    - adres: String
    - nip: String
    + Sklep(nazwa: String, adres: String, nip: String)
    + podajDane(): String
    + podajAdres(): String
    + podajNIP(): String
}

class Produkty {
    - produkt: String
    - ilosc: int
    - cena: double
    + Produkty(produkt: String, ilosc: int, cena: double)
    + podajCenaNetto(): double
    + podajWartoscVAT(): double
    + podajCene(): double
    + podajIlosc(): int
    + podajProdukt(): String
    + toString(): String
}

Main --> Faktura
Main --> Sklep
Main --> Produkty
Faktura --> Sklep
Faktura --> Produkty

@enduml
