@startuml

left to right direction

actor User as U

rectangle "Program" {
    usecase "Pokaż koszyk" as UC1
    usecase "Dodaj samochody" as UC2
    usecase "Wystaw fakturę" as UC3
    usecase "Dostępne samochody" as UC4
    usecase "Wyjście" as UC5
}

U --> UC1 : Wybiera
U --> UC2 : Wybiera
U --> UC3 : Wybiera
U --> UC4 : Wybiera
U --> UC5 : Wybiera

@enduml
